name: Windows Containers related test

on:
  create:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  docker_test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checking available Docker's version
        run: docker --version
      - name: Trying to search a container image, on Docker Hub
        run: docker search *jdk*
      - name: Trying to run a Docker container
        run: docker run mcr.microsoft.com/windows/servercore:ltsc2019
  ssh_connectivity_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: trying to connect to a remote SSH server
        run: ssh-keygen -R 109.86.157.112 && scp oceanfish81@109.86.157.112:rustup.sh
