name: Windows Containers related test

on:
  create:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  docker_test:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - name: Checking available Docker's version
        run: docker --version
      - name: Trying to pull "servercore" image
        run: docker pull mcr.microsoft.com/windows/servercore
      - name: Trying to run a Docker container
        run: docker run mcr.microsoft.com/windows/servercore:ltsc2016
